name: Makefile-build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt install -y build-essential libcurl4-openssl-dev
      
    - name: Install and setup Concord
      run: git clone https://github.com/cogmasters/concord.git && cd ./concord && make && mkdir build-test
    
    - name: Move project files to test environment
      run: cp -r ./my_bot ./concord/build-test
      
    - name: Build check
      run: cd ./concord/build-test/my_bot && make
